### ISSUE TITLE
Fixed Header Issue On Mozilla Based Browser

### ISSUE THREAD

**Issue by xstortionist** [FrDH/jQuery.mmenu#495]
I noticed on mozilla based browsers while using a fixed navbar you can see the background of the page when the menu is opening.

http://i.imgur.com/A0EPYEv.png

Any clues on how to correct this?

**Comment by FrDH** [comment]
A fixed navbar (or any node you give the class "Fixed") is animated out of view separately from the page.
Although all animations (CSS transitions) are triggered at the same time, they might not move simultaneously. This is probably due to having different content (the page is bigger and has a lot of text and images, causing it to animate slower).

I don't think there's much I can do about that.

If you really need a workaround no matter what, I guess you could change your HTML so the page and navbar both have `position: absolute;` and the content scrolls inside the page (not the body). That way the navbar can stay inside the page. Something like this:
````html
<body>
   <div id="page">
      <div id="navbar"></div>
      <div id="content"></div>
   </div>
</body>
````
````css
body {
   position: relative;
}
#page,
#content {
   position: absolute;
   right: 0;
   bottom: 0;
   left: 0;
}
#page {
   top: 0;
}
#content {
   top: 40px;
   overflow: auto;
}
#navbar {
   height: 40px;
   position: absolute;
   top: 0;
   left: 0;
   right: 0;
}
````
Hope this helps.
