### ISSUE TITLE
eventlistener for menuclose/menuopen

### ISSUE THREAD

**Issue by dstN** [FrDH/jQuery.mmenu#508]
how can i find out when the menu is opened and when it gets closed? 

i need to know or listen to that event to add/remove Classes from elements, so i can switch between hamburger-button and close-button.

**Comment by FrDH** [comment]
You can use the [API](http://mmenu.frebsite.nl/documentation/api.html) to bind new functions to the `open`, `opening`, `opened`, `close`, `closing` and `closed` methods.

If it's just for CSS, I'd recommend using CSS :)
````css
#hamburger {
   display: block;
}
#close {
   display: none;
}

html.mm-opened #hamburger {
   display: none;
}
html.mm-opened #close {
   display: block;
}
````
