### ISSUE TITLE
Use mmenu only in submenu dropdown

### ISSUE THREAD

**Issue by huersch** [FrDH/jQuery.mmenu#534]
Hi,

thanks for the great script.

I try to use mmenu in a desktop view.
I have a main navigation which triggers a dropdown menu (via bootstraps dropdown.js).

In the dropdown the first submenu should be an mmenu and open it't submenus in the same container.

Can I achieve this with mmenu?

**Comment by FrDH** [comment]
Hi,

I guess something like that should be possible, but it would probably require some specific HTML for the menu. Here's something to get you started.

HTML
````html
<nav id="menu">
   <ul>
      <li><a href="/">main item</a>
         <!-- this extra DIV around the UL is required -->
         <div>
            <ul>
               <li><a href="/">sub item</a>
                  <!-- sub sub, sub sub sub, etc -->
               </li>
            </ul>
         </div>
      </li>
   </ul>
</nav>
````


CSS
````css
#menu > ul > li {
   position: relative;
}
/* because the plugin needs to measure the height, display: none; probably won't work */
#menu > ul > li > div {
   top: -10000px;
   left: -10000px;
}
#menu > ul > li:hover > div {
   top: 100%;
   left: 0;
}
````


JS
````javascript
$("#menu > ul > li > div").mmenu({
   offCanvas: false,
   autoHeight: true
})
````

Hope this helps.
