### ISSUE TITLE
My menu isn't responsive 

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#558]
I did a web app, I cloned the menu and I also put the media queries as it is suggested in
http://mmenu.frebsite.nl/support/tips-and-tricks.html. However, it didn't work, I attach the image from the cell phone.
I noticed one id is prepended with mm and the other it isn't. Is it right?

@media (max-width: 600px) {
   #my-menu {
      display: none !important;
   }
}
@media (min-width: 601px) {
   #mm-my-menu{
      display: none !important;
   }
}

I appreciate any help with it.

Thanks in advance :)

![screenshot_2016-04-18-16-48-09](https://cloud.githubusercontent.com/assets/1948071/14619630/ba4b3a8a-058e-11e6-8f93-64195e0c4933.png)

**Comment by FrDH** [comment]
I had a look at the website and notices in your CSS:
````css
.mm-menu {
    width: 60% !important;
}
````
If you're going to change the width, you should also change some other values:
````css
html.mm-opening .mm-slideout {
  -webkit-transform: translate(80%, 0);
  -moz-transform: translate(80%, 0);
  -ms-transform: translate(80%, 0);
  -o-transform: translate(80%, 0);
  transform: translate(80%, 0); }

@media all and (max-width: 175px) {
  html.mm-opening .mm-slideout {
    -webkit-transform: translate(140px, 0);
    -moz-transform: translate(140px, 0);
    -ms-transform: translate(140px, 0);
    -o-transform: translate(140px, 0);
    transform: translate(140px, 0); } }
@media all and (min-width: 550px) {
  html.mm-opening .mm-slideout {
    -webkit-transform: translate(440px, 0);
    -moz-transform: translate(440px, 0);
    -ms-transform: translate(440px, 0);
    -o-transform: translate(440px, 0);
    transform: translate(440px, 0); } }
````
There's a SCSS mixin you can use to automagically create this CSS:
http://mmenu.frebsite.nl/documentation/custom-css/custom-sizes.html
