### ISSUE TITLE
How to change the check button color

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#562]
Hi, I want them to be more clear, I overwritten some default values with no luck.
```
.mm-menu label.mm-check:before {
  border-color: rgba(235, 255, 237, 1.0) !important; }    
```

I could set another values in this way. I appreciate any suggestion about how to tweak.
Thanks
![check](https://cloud.githubusercontent.com/assets/1948071/14805231/5b18b6de-0b40-11e6-99cf-42a4d6e562e5.png)

**Comment by FrDH** [comment]
Have a look at the SCSS section in the docs:
http://mmenu.frebsite.nl/documentation/addons/toggles.html

You could either [override the SCSS variables](http://mmenu.frebsite.nl/documentation/custom-css/override-variables.html) or [use the mixin](http://mmenu.frebsite.nl/documentation/custom-css/custom-colors.html) to create some new CSS.

But since the CSS for the toggles and checks are pretty straight forward, I'd suggest you simply override the colors in your own stylesheet using plain old CSS.

Hope this helps.

**Comment by rossanag** [comment]
Yes, I think overriding is pretty straightforward. I was trying to override the colors, but I don't know what I am doing wrong. Indeed I want to change the color of the check mark button before it is checked.
Which is the class to change? I was tweaking. Thanks!
```
.mm-menu label.mm-check:before {
  border-color: rgba(235, 255, 237, 1.0) !important; }    

```

**Comment by FrDH** [comment]
Here's some sample CSS that I think should work:
````css
label.mm-check:before {
   border-color: blue !important;
   opacity: 1 !important;
}
input.mm-check:checked ~ label.mm-check:before {
   border-color: pink !important;
   opacity: 1 !important;
}
````
