### ISSUE TITLE
Mobile issue open right menu (.mm-right) not stretched

### ISSUE THREAD

**Issue by claudchan** [FrDH/jQuery.mmenu#570]
I tested when using "open right menu" on mobile device (android) the class ".mm-right" doesn't have top zero and bottom zero. The result issue, the mmenu height is equal to zero height and leave the content as blank (empty). Can someone confirm this, besides me?

Original mmenu style:
.mm-menu.mm-right {
    left: auto;
    right: 0;
}

My workaround solutions:
.mm-menu.mm-right {
    left: auto;
    right: 0;
    top: 0;
    bottom: 0;
}

**Comment by FrDH** [comment]
I had a look at the (latest) demo and found this CSS:
````css
.mm-menu,
.mm-panels,
.mm-panels > .mm-panel {
    margin: 0;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    z-index: 0;
    box-sizing: border-box;
}
````

Effectively setting the `top`, `bottom` and `right` to `0`
