### ISSUE TITLE
offset from top of browser window

### ISSUE THREAD

**Issue by fastnetwebdesign** [FrDH/jQuery.mmenu#584]
I am using:

```
"offCanvas": {
   "position": "left",
   "zposition" : "front"
},
```

Is there any way to offset the menu from the top of the browser window - i.e. by 200px?

I've tried margin's, etc and it auto scrolling the page up.

**Comment by FrDH** [comment]
You should be able to change the `top` value:
````css
.mm-menu {
    top: 200px !important;
}
````
