### ISSUE TITLE
mm.title multiline

### ISSUE THREAD

**Issue by worm1** [FrDH/jQuery.mmenu#590]
Hi , 
I don't want to truncate the text to a single line so i include the "multiline" extension .css file and add "multiline" to the extensions option. It s work fine for the list items but not for the title on top of the menu.

How can i put the title in multiline ?

Thanks !!!

**Comment by FrDH** [comment]
The multiline extension only applies to the list items in a listview (LI in an UL). 
I guess you could remove the truncation from the title, but the navbar it is in will not automatically resize.
To remove the truncation, just override any of the associated CSS:
````css
.mm-title {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}
````
