### ISSUE TITLE
Setting width without SCSS

### ISSUE THREAD

**Issue by mardanlin** [FrDH/jQuery.mmenu#643]
Having paid for a license I was really hoping this would be a feature by now. For those of us working in settings without SASS compilers, this is a huge headache. Why is there not just a setting in the JS like every other menu? 

In your tutorial, you do not even include the variables file needed to generate the custom CSS to override the old style. This is just not a good practice, are there any plans to fix this or at least update the tutorial to be usable?

**Comment by FrDH** [comment]
Hi,

The width is not a fixed value, it is a percentage with a min and max value. Doing that with a setting would need an onWindowResize event to constantly check the available width. Using CSS is just way more efficient in this case.

I had a look at the documentation on how to override variables and found they are out of date. They should have been updated after switching to Gulp as a task runner.
I'll update the documentation shortly.

If you're looking for a non-SASS solution, you should be able to override the following CSS:
````css
.mm-menu.mm-offcanvas {
   width:80%;
   min-width:140px;
   max-width:440px;
}
html.mm-opening .mm-slideout {
   -webkit-transform:translate(80%,0);
         -ms-transform:translate(80%,0);
                 transform:translate(80%,0);
   -webkit-transform:translate3d(80%,0,0);
                 transform:translate3d(80%,0,0)
}

/* 140 / 0.8 = 175 */
@media all and (max-width:175px) {
   html.mm-opening .mm-slideout {
      -webkit-transform:translate(140px,0);
            -ms-transform:translate(140px,0);
                    transform:translate(140px,0);
      -webkit-transform:translate3d(140px,0,0);
                   transform:translate3d(140px,0,0)
   }
}

/* 440 / 0.8 = 550 */
@media all and (min-width:550px) {
   html.mm-opening .mm-slideout{
      -webkit-transform:translate(440px,0);
            -ms-transform:translate(440px,0);
                    transform:translate(440px,0);
      -webkit-transform:translate3d(440px,0,0);
                   transform:translate3d(440px,0,0)
   }
}
````

Hope this helps.
