### ISSUE TITLE
Help for fullscreen with offset

### ISSUE THREAD

**Issue by Webtransformer** [FrDH/jQuery.mmenu#656]
First thanks for this really great script!
I played with some of the options and achieved what I wanted but I think it´s not the best way to do it.
Used offcanvas from the top with zposition front and changed some css values (top position to achieve a offset and height 100%)

This is what I wanted:
On click on the hamburger icon the mmenu opens fullscreen with the offset from the top to show the fixed header. I am not sure which options are the best for this (offcanvas, dropdown etc). Can you give me a hint?
<img src="http://www.webtransformer.de/images/mm1.png"/>
<img src="http://www.webtransformer.de/images/mm2.png"/>

**Comment by FrDH** [comment]
There's no "offset" option by default, mainly because that would require CSS that can't be calculated by default.

The following CSS would probably be all you need to override:
````css
.mm-menu {
   top: 40px;
   height: calc( 100% - 40px );
   min-height: calc( 100% - 40px );
   max-height: calc( 100% - 40px );
}
````
You might also want to hide the "blocker" DIV that closes the menu when clicked:
````css
#mm-blocker {
   display: none;
}
````
And change the z-index for your header, so it will be in front of the menu:
````css
#my-header {
   z-index: 5;
}
````

Hope this helps
