### ISSUE TITLE
multi-line title

### ISSUE THREAD

**Issue by sensaetions** [FrDH/jQuery.mmenu#744]
Hello,

I am aware of [this ticket](https://github.com/FrDH/jQuery.mmenu/issues/590), but it didn't answer one of my questions. 

Currently the `.mm-title` height is set to 40px.  Can you explain how I can go about making the title have a variable height, and push down the list menus beneath it? 

Or make it so that the height of the `.mm-navbar` adapts to the height of the multi-lined contents of the `.mm-title`?  Is it possible to make the navbar automatically resize its height to the height of the title?

**Comment by FrDH** [comment]
The title can not automatically resize its height. You could enable it to be scrollable by adding this CSS:
````css
.mm-navbar .mm-title {
   overflow: auto;
   -webkit-overflow-scrolling: touch
}
````

Hope this helps.
