### ISSUE TITLE
page content scales in width when opening

### ISSUE THREAD

**Issue by mpitz** [FrDH/jQuery.mmenu#752]
When opening the mmenu and the page has a scroller the scroller is removed and the (responsive) page content scales in width to the new width without the scroller. This makes the page content "jumping".

I know it's because the scroller is removed and therefore the width is changed. I know we can do something like:

```css
html.mm-opened {
	overflow: auto !important;
}
```

But than we've a scroller in the menu as well. Perhaps the module can determine the with of the scroller and inject an offset at the side of the content the menu is opened?

**Comment by FrDH** [comment]
The scrollbar disappears because the user should not be able to interact with the rest of the page while the menu is opened. You can change this behavior by setting the `offCanvas.blockUI` option to `false`:
http://mmenu.frebsite.nl/documentation/core/off-canvas.html

If you don't want  the user to be able to interact with the rest of the page, I guess you could also manually override the CSS:
````css
html.mm-opened #page {
    overflow: auto !important;
}
````

Hope this helps.
