### ISSUE TITLE
IE11 - Fixed Header not showing correctly

### ISSUE THREAD

**Issue by simdine** [FrDH/jQuery.mmenu#786]
Hello,

I have a fixed header.

If i add a className : fixed, it disapears. It works fine without a fixed className. But only IE11 Doesn't move the fixed header to right side. please check the image
https://ibb.co/d2gZP5

However, the other browsers seem to wrok fine, please check the screen
https://ibb.co/jsPhBk

What i did to send the header back to menu
my css :
.header {z-index: 1}
I had to edit the mmenu css file 
#mm-blocker {z-index: 3}
 .mm-menu.mm-offcanvas{z-index:2}
This hack is sending the header back, but it doesn't move it to the right side, see the result
https://ibb.co/d0JTZ5

How to fix this IE bug ?

**Comment by simdine** [comment]
Please, don't click on the link, copy/past on the browser

Thanks

**Comment by FrDH** [comment]
Is there an online example I could have a look at?

**Comment by simdine** [comment]
It's working on localhost, i don't know why this JS Fiddle doesn't work. here is here the code:

https://jsfiddle.net/bn5z405t/

**Comment by simdine** [comment]
I fixed the issue, there was an error in my code. Sorry.

Just to be sure, I would like to use a pageSelector and classNames. they should be in this way ?
$("#bar").mmenu({
         //options
}, {
         //Config
         classNames: {
	         fixedElements: {
		         fixed: "fix"
                 }
          },
          offCanvas: {
	         pageSelector: "#page"
          }
});
var API = $("#bar").data("mmenu");

Is there an error ?

**Comment by FrDH** [comment]
That seems to be correct, is t not working?

**Comment by simdine** [comment]
It's working.
last thing, i would like to add an image and icons left and right like this http://mmenu.frebsite.nl/demo/index.html?demo=menu-advanced-4

But there's no a tuto for that, step by step.

Can you help me ? in private ?

**Comment by FrDH** [comment]
That example uses a lot of custom CSS, [view the source](view-source:http://mmenu.frebsite.nl/demo/index.html?demo=menu-advanced-4) to see the additional CSS.

The part that makes the navbar look like that:
````css
.mm-menu  .mm-navbar-size-2 {
   text-align: center;
   position: relative;
   border-bottom: none;
}
.mm-menu  .mm-navbar-size-2:before {
   content: "";
   display: inline-block;
   vertical-align: middle;
   height: 100%;
   width: 1px;
}
.mm-menu .mm-navbar-size-2 > * {
   display: inline-block;
   vertical-align: middle;
   float: none;
}
.mm-menu .mm-navbar-size-2 a {
   border: 1px solid rgba(255, 255, 255, 0.6);
}
.mm-menu .mm-navbar-size-2 img {
   opacity: 0.6;
   border: 1px solid #fff;
   border-radius: 60px;
   width: 60px;
   height: 60px;
   padding: 10px;
   margin: 0 10px;
}
.mm-menu .mm-navbar-size-2 a {
   border-radius: 40px;
   color: rgba(255, 255, 255, 0.8) !important;
   font-size: 16px !important;
   line-height: 40px;
   width: 40px;
   height: 40px;
   padding: 0;
}
.mm-menu .mm-navbar-size-2 a:hover {
   border-color: #fff;
   color: #fff !important;
}
````

And the JS:
````js
$("#menu").mmenu({
   navbars : [{
      height : 2,
      content : [ 
         '<a href="#/" class="fa fa-phone"></a>',
         '<img src="img/profile-2-w.png" />',
         '<a href="#/" class="fa fa-envelope"></a>'
      ]
   }]
});
````

Hope this helps.
