### ISSUE TITLE
Closing offcanvas menu also momentarily removes oncanvas menu

### ISSUE THREAD

**Issue by smth** [FrDH/jQuery.mmenu#801]
If you have both an oncanvas and offcanavs menu on the same page, clicking to close the offcanavs menu also causes the oncanvas menu to disappear momentarily.

Example here: https://codepen.io/anon/pen/NabJYE

As there's no need for an oncanvas menu to "close", could they be excluded from this action?

**Comment by FrDH** [comment]
Hi,

Thank you for reporting this issue. It appears to occur only when having an off-canvas menu that uses the dropdown add-on. I'll see if I can find the bug and fix it.

**Comment by FrDH** [comment]
Found the bug:
````css
html.mm-dropdown.mm-opened:not(.mm-opening) .mm-menu
{
	display: none;
}
````
That probably should be:
````css
html.mm-dropdown.mm-opened:not(.mm-opening) .mm-menu.mm-dropdown
{
	display: none;
}
````
Will fix this in the next version. 
For now, you can add this line of CSS:
````css
html.mm-dropdown.mm-opened:not(.mm-opening) .mm-menu:not(.mm-dropdown)
{
	display: block;
}
````
