### ISSUE TITLE
Column layout scrolling text upon submenu expansion

### ISSUE THREAD

**Issue by srivest** [FrDH/jQuery.mmenu#808]
Hi,

This is best described through a video capture:

https://drive.google.com/file/d/0B36-VAkgjJaWWjdZbndkVDY2eW8/view

Basically, as I press a top menu item with subtext to see its children, the subtext scrolls as the menu width rearrange itself. Of course this only occurs with the multiline plugin enabled. 

Any idea on how to prevent this from happening?

**Comment by FrDH** [comment]
I don't think you can prevent text from wrapping like that while the width of its parent is animated.
So you probably should look into how not to animate the widths:
````css
.mm-coluns {
    transition-property: none;
}
.mm-columns .mm-panels > .mm-panel {
    transition-property: transform;
}
````
Removing the animation doesn't really give a nice result though :(

Another way to get rid of the animating width is to set a fixed number of visible columns:
````js
$("#my-menu").mmenu({
   columns: 3
})
````
Hope this helps.
