### ISSUE TITLE
Can I enable the users use the page while the mmenu is open in mmenu V4.2.0 ?

### ISSUE THREAD

**Issue by eshiett1995** [FrDH/jQuery.mmenu#884]

**Comment by FrDH** [comment]
Not by default in 4.2.0, but I guess you could override the CSS for the `div#mm-blocker` so it isn't visible.
````css
#mm-blocker
{
   display: none !important;
}
````
