### ISSUE TITLE
Bootstrap 3/4 Modal box issue

### ISSUE THREAD

**Issue by nuryagdym** [FrDH/jQuery.mmenu#898]
Hi, 
Modal box are not working properly with mmenu when I put modal box code inside wrapper element (pageSelector). Modalboxes overlayed with its backdrop layer. 
Without mmenu modals work properly.
here is fiddle: https://jsfiddle.net/5nk6132p/9/

**Comment by FrDH** [comment]
Try adding this CSS:
````css
body.modal-open .mm-slideout
{
    z-index: unset;
}
````

I'll see if I can implement this fix in the Bootstrap wrapper.
