### ISSUE TITLE
IE 11 doesn´t load theme-dark

### ISSUE THREAD

**Issue by reynaldomega** [FrDH/jQuery.mmenu#935]
I've configured mmenu with the extension 'theme-dark'. 
It's working well with chrome, firefox and edge but when I try to open a page that contains the mmenu with IE 11 it always shows the default white background color.

**Comment by FrDH** [comment]
The themes are completely created with CSS variables, IE11 and down don't support CSS variables,
therefor the menu defaults to the default values.
If you absolutely need the theme to work in IE11, you can override the SCSS variables in a custom build: http://mmenu.frebsite.nl/documentation/custom-build.html
Or, if you're looking for a quick-fix, you could manually override the CSS:
````css
.mm-menu {
    background: #333;
    color: #fff
}
.mm-listitem,
.mm-navbar {
   border-color: #fff;
}
````
