### ISSUE TITLE
styled tooltips on iconbar 

### ISSUE THREAD

**Issue by bkeklikoglu** [FrDH/jQuery.mmenu#950]
Hello,

I'd like to add styled tooltips for icons on iconbar but I could not show tooltips when menu is closed because of z-index of main div bigger than mmenu. If I change it another problem appears. How can i handle it? Thanks for help , you can see the demo below; 
https://jsfiddle.net/berkeke/6a7nr1xv/
@FrDH

**Comment by FrDH** [comment]
Hi,

This can only work if you set the menu to be positioned absolute. So the below will work, but looks really odd if your page is longer and you scroll down.
````css
.mm-menu {
    position: absolute;
    z-index: unset;
}
.mm-iconbar {
    z-index: unset;
    overflow: visible;
}
.mm-menu__blocker {
   display: none;
}
````
(add an "!important" where needed to override the plugin CSS)

Another approach (that does allow your page to be longer and scrollable), would be to add the tooltips to the <body> and position them using javascript.

Hope this helps.
